# Properties for Transaction Service
server.port=9002

# Database Configuration for this service
spring.datasource.url=jdbc:postgresql://localhost:5432/transaction_db
spring.datasource.username=rajeshs019
spring.datasource.password=rajeshs019

# Logging
logging.level.com.rajesh=DEBUG