# Properties for User Service
server.port=9001

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=rajeshs019
spring.datasource.password=rajeshs019

# Secret key for signing JWT tokens. In a production environment, use a more secure key.
jwt.secret=4f18b5e9a4f44c6b8c9d0e2f1b3e5d7a8c6b3e5d7f2a1b4e6f8c9d0e2f1b3e5d

# Logging
logging.level.com.rajesh=DEBUG